### ISSUE TITLE
Getting undefined local variable or method `currency' when trying to Withdraw

### ISSUE THREAD

**Issue by raulgobr** [Lowest0ne/poloniex#4]
I am getting this error: "undefined local variable or method `currency' for Poloniex:Module, line 72 in poloniex.rb.

Any clue how to correct this?

**Comment by Lowest0ne** [comment]
I must admit, I've been away for a while.  Yes, I had a typo in there.  PabiGamito's pull request fixes it, but I'm still going to need a bit of time to brush the dust off this repo.

**Comment by Lowest0ne** [comment]
Pablo Gamito has fixed this with https://github.com/Lowest0ne/poloniex/commit/9632a91abd385802406ab6592522ef3a9c3775c4
